version: '2'

services:
  postgres:
    image: postgres:9.5
    container_name: play-react-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=originate
      - POSTGRES_TEST_DB=test
      - POSTGRES_USER=originate
      - POSTGRES_PASSWORD=password
    volumes:
      - ./tmp/postgres-data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d

  statsd:
    image: datadog/docker-dd-agent
    environment:
      API_KEY: "testkey"
    ports:
      - "8125:8125/udp"
